### ISSUE TITLE
关于显示评测状态

### ISSUE THREAD

**Issue by ZoneLikeWonderland** [ShanghaitechGeekPie/oj-frontend#13]
是否考虑在submission里显示评测状态？比如正在评测，或者两次提交时间间隔过小，或者以后可能出现的情况。
现在的序列化会返回('state', 'commit_tag', 'score', 'overall_score', 'message', 'assignment_id', 'submission_time', 'delta')
其中state取值暂定如下
    # |     state    | integer |
    # --------------------------
    # |   PLACEHOLD  |    0    |
    # |    PENDING     |    1    |
    # |    JUDGED       |    2    |
    # |    INVALID       |    3    |

或者塞到每个提交的message里也可以，但是那样不能直观显示。

**Comment by philipxyc** [comment]
为submission detail页面再开一列显示即可 @Artanic30 

@ZoneLikeWonderland @EricDiao 修改之后还需修改scoreboard界面的后端API，之前的逻辑是“取最新的record作为成绩显示”，现在需要修正成“取最新的并且状态为判卷完成（或分数不为空）”。其他具有相类似逻辑的api也需要相应修正

**Comment by Artanic30** [comment]
好的，我尽快改

**Comment by Artanic30** [comment]
最终后端api是返回什么数据

**Comment by ZoneLikeWonderland** [comment]
目前是
`/student/<str:student_id>/course/<str:course_id>/assignment/<str:assignment_id>/history/`
返回所有的记录

`/student/<str:student_id>/course/<str:course_id>/assignment/`
`/course/<str:course_id>/assignment/<str:assignment_id>/scores/`
`/student/<str:student_id>/course/<str:course_id>/assignment/<str:assignment_id>/scores/`
是返回state=2的记录

**Comment by philipxyc** [comment]
补充，最下面两个api返回的是state=2的记录最后一次提交情况。

另外龙哥你还要把两个api返回的json样式在readme里面修改一下

顺颂 商祺
夏寅岑

________________________________

**Comment by Artanic30** [comment]
/student/<str:student_id>/course/<str:course_id>/assignment/<str:assignment_id>/history/
有status参数是按你最上面写的对吧

**Comment by ZoneLikeWonderland** [comment]
是

**Comment by Artanic30** [comment]
https://github.com/ShanghaitechGeekPie/oj-frontend/pull/18
