### ISSUE TITLE
Entrypoint of "Claiming Identity" is hard to find and the implementation may be wrong

### ISSUE THREAD

**Issue by EricDiao** [ShanghaitechGeekPie/oj-frontend#16]
The `oj-backend` provides an interface for users to claiming their identity through a POST request. The frontend shall provide an easy-to-find interface for user to perform this action. But now the interface is not so easy for a beginner to find which will bring confusion to beginners.

Also, @ZoneLikeWonderland found that using this interface always results in a HTTP 405 (Unsupported Method) from backend (but directly accessing it results in a success result). Please check if the implememntation used the right method and formed the correct payload.

**Comment by ZoneLikeWonderland** [comment]
`https://oj.geekpie.club/undefined/user/bcd7ee2a-0778-11ea-b059-029eb884e60b/student` should be `https://oj.geekpie.club/api/user/bcd7ee2a-0778-11ea-b059-029eb884e60b/student`

**Comment by Artanic30** [comment]
https://github.com/ShanghaitechGeekPie/oj-frontend/pull/17
